export enum DeliveryStatus {
  PENDING_DISPATCH = 'PENDING_DISPATCH',
  OFFERING = 'OFFERING',
  ASSIGNED = 'ASSIGNED',
  REASSIGNING = 'REASSIGNING',
  PICKED_UP = 'PICKED_UP',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  ARRIVING = 'ARRIVING',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
