export enum CheckoutErrorCode {
  CART_EMPTY = 'CART_EMPTY',
  SHOP_UNAVAILABLE = 'SHOP_UNAVAILABLE',
  SHOP_SUSPENDED = 'SHOP_SUSPENDED',
  PRODUCT_UNAVAILABLE = 'PRODUCT_UNAVAILABLE',
  PRODUCT_DISCONTINUED = 'PRODUCT_DISCONTINUED',
  ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',
  ADDRESS_NOT_OWNED = 'ADDRESS_NOT_OWNED',
  OUTSIDE_DELIVERY_RADIUS = 'OUTSIDE_DELIVERY_RADIUS',
  MINIMUM_ORDER_NOT_MET = 'MINIMUM_ORDER_NOT_MET',
  INVALID_CART_ITEM = 'INVALID_CART_ITEM',
}
